# Generated by Django 5.2.1 on 2025-05-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("erkak", "Erkak"), ("ayol", "Ayol"), ("bolalar", "Bol
alar")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(),
        ),
    ]
