# Generated by Django 5.2.1 on 2025-05-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0002_remove_product_description_alter_product_category_and
_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("pending", "Kutilmoqda"), ("delivered", "Yetkazildi")
],
                default="pending",
                max_length=20,
            ),
        ),
    ]
