# Generated by Django 5.2.1 on 2025-05-20 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0003_rename_order_date_order_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="crm_app.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(),
        ),
    ]
